DROP table IF EXISTS compilation_event, compilations, requests, events, users, categories;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(254) NOT NULL,
  name VARCHAR(250) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(500) NOT NULL,
  category_id BIGINT,
  description VARCHAR(1000),
  exist_date TIMESTAMP,
  create_date TIMESTAMP,
  publish_date TIMESTAMP,
  location_lat DOUBLE PRECISION,
  location_lon DOUBLE PRECISION,
  paid BOOLEAN,
  participant_limit INT,
  request_moderation BOOLEAN,
  state VARCHAR(10),
  title VARCHAR(500),
  views BIGINT,
  CONSTRAINT pk_event PRIMARY KEY (id),
  CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_id BIGINT,
  requester_id BIGINT,
  status VARCHAR(10),
  create_date TIMESTAMP,
  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT fk_requests_to_events FOREIGN KEY(event_id) REFERENCES events(id),
  CONSTRAINT fk_requests_to_users FOREIGN KEY(requester_id) REFERENCES users(id)
  );

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned BOOLEAN,
  title VARCHAR(50),
  CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event (
  compilation_id BIGINT,
  event_id BIGINT,
  CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id),
  CONSTRAINT fk_compilation_event_to_events FOREIGN KEY(event_id) REFERENCES events(id),
  CONSTRAINT fk_compilation_event_to_compilations FOREIGN KEY(compilation_id) REFERENCES compilations(id)
);
