DROP table IF EXISTS views, compilation_event, compilations, requests, events, users, categories;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(254) NOT NULL,
  name VARCHAR(250) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT,
  initiator_id BIGINT,
  description VARCHAR(7000),
  exist_date TIMESTAMP,
  create_date TIMESTAMP,
  publish_date TIMESTAMP,
  location_lat DOUBLE PRECISION,
  location_lon DOUBLE PRECISION,
  paid BOOLEAN,
  participant_limit INT,
  request_moderation BOOLEAN,
  state VARCHAR(10),
  title VARCHAR(120),
--  views BIGINT,
  CONSTRAINT pk_event PRIMARY KEY (id),
  CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(id),
  CONSTRAINT fk_events_to_users FOREIGN KEY(initiator_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_id BIGINT,
  requester_id BIGINT,
  status VARCHAR(10),
  create_date TIMESTAMP,
  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT fk_requests_to_events FOREIGN KEY(event_id) REFERENCES events(id),
  CONSTRAINT fk_requests_to_users FOREIGN KEY(requester_id) REFERENCES users(id)
  );

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned BOOLEAN,
  title VARCHAR(50),
  CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event (
  compilation_id BIGINT,
  event_id BIGINT,
  CONSTRAINT pk_compilation_event PRIMARY KEY (compilation_id, event_id),
  CONSTRAINT fk_compilation_event_to_events FOREIGN KEY(event_id) REFERENCES events(id),
  CONSTRAINT fk_compilation_event_to_compilations FOREIGN KEY(compilation_id) REFERENCES compilations(id)
);

CREATE TABLE IF NOT EXISTS views (
    event_id BIGINT,
    user_ip VARCHAR(30),
    CONSTRAINT pk_view PRIMARY KEY (event_id, user_ip),
    CONSTRAINT fk_view_to_events FOREIGN KEY(event_id) REFERENCES events(id)
);
